config/routes.rb
Rails.application.routes.draw do
  get 'pharmacist/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'static_pages/home'
  get  '/about',   to: 'static_pages#about'
  get  '/services', to: 'static_pages#services'
  get  '/signup',    to: 'pharmacist#new'
  post '/signup',  to: 'pharmacist#create'
  root 'static_pages#home'
  resources :pharmacist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello world"
  end
end

app/controllers/pharmacist_controller.rb
class PharmacistController < ApplicationController
  def new
    @pharmacy = Pharmacy.new
  end

  def show
    @pharmacy = Pharmacy.find(params[:id])
    #debugger
  end

  def create
    @pharmacy = Pharmacy.new(pharmacy_params)
    if @pharmacy.save
      flash[:success] = "Welcome Kayak pharmacy systems!"
      redirect_to pharmacist_path(@pharmacy)
    else
      render 'new'
    end

  end

  private

    def pharmacy_params
      params.require(:pharmacy).permit(:name, :pharmacy_name, :email, :region, :location, :address, :password,
                                   :password_confirmation)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def services

  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pharmacist_helper.rb
module PharmacistHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="panel-footer">
  <div class="container">
    <div class="row">
      <section id="hours" class="col-sm-4">
        <span>Info</span><br>
        regisetered with WWP<br>
        Experts available
        <hr visible-xs>
      </section>

      <section id="hours" class="col-sm-4">
        <span>Info</span><br>
        regisetered with WWP<br>
        Experts available
        <hr visible-xs>
      </section>

      <section id="hours" class="col-sm-4">
        <span>Info</span><br>
        regisetered with WWP<br>
        Experts available
        <hr visible-xs>
      </section>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav id="header-nav" class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a href="index.html" class="pull-left visible-md visible-lg">
          <div id="logo-img" alt="Logo Image"></div>
        </a>

        <div class="navbar-brand">
            <a href="index.html" class="pull-rights">
              <h1>KAYAK</h1>
              <p><span>Pharmaceutical company limited</span></p>
            </a>
        </div>

        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsable-nav" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div id="collapsable-nav" class ="collapse navbar-collapse">
        <ul id="nav-list" class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   "/"%></li>
          <li><%= link_to "About",   about_url %></li>
          <li><%= link_to "Services",   services_url %></li>
          <li id="phone" class="hidden-xs">
            <a href="tel:233-050-525-7947">
              <span>050-525-7947</span></a><div>* Hotline</div>
          </li><!--nav-list-->
        </ul><!--.collapse .navbar-collapse -->
      </div>

    </div>
  </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:title) %> | Kayak management systems</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,
      initial-scale=1">
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pharmacist/new.html.erb
<% provide(:title, 'Sign up') %>
<div id="main-content" class="container">



<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Sign up</h1>
    <br>
    <p>Click the button to autofill your location.</p>

    <button onclick="getLocation()">Try It</button>
    <p id="demo"></p>
    <p id="geo"></p>

    <%= form_for @pharmacy, url: {action: "create"} do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :pharmacy_name %>
      <%= f.text_field :pharmacy_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :region %>
      <%= f.text_field :region, class: 'form-control', list: 'region', id: 'reg' %>
      <datalist id="region">
        <option value="Greater-Accra">
        <option value="Volta">
        <option value="Ashanti">
        <option value="Eastern">
        <option value="Western">
        <option value="Brong-Ahafo">
        <option value="Nothern">
        <option value="Upper-East">
        <option value="Upper-West">
        <option value="Central">
      </datalist>



      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control', id:'loc' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control', id:'addr' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>

    <script>
    var x = document.getElementById("demo");


    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);

        } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
        }
    }

    function showPosition(position) {

        getReverseGeocodingData(position.coords.latitude, position.coords.longitude)
    }

          function getReverseGeocodingData(lat, lng) {
          var latlng = new google.maps.LatLng(lat, lng);
          // This is making the Geocode request
          var geocoder = new google.maps.Geocoder();
          geocoder.geocode({ 'latLng': latlng }, function (results, status) {
              if (status !== google.maps.GeocoderStatus.OK) {
                  alert(status);
              }
              // This is checking to see if the Geoeode Status is OK before proceeding
              if (status == google.maps.GeocoderStatus.OK) {
                  console.log(results);
                  //x.innerHTML = (results[0].formatted_address);
                  //y.innerHTML = (results[1].formatted_address);

                      document.getElementById('reg').value = (results[0].address_components[4].short_name);
                      document.getElementById('loc').value = (results[0].address_components[2].short_name);
                      document.getElementById('addr').value = (results[0].address_components[0].short_name) + " " + (results[0].address_components[1].short_name) + " " + (results[0].address_components[3].short_name);

              }
          });
      }
    </script>

  </div>
</div>
</div>
<br>

app/views/pharmacist/show.html.erb
<%= provide(:title, @pharmacy.name) %>
<div id="main-content" class="container">
  <%= @pharmacy.name %>, <%= @pharmacy.email %>
</div>

app/views/shared/_error_messages.html.erb
<% if @pharmacy.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@pharmacy.errors.count, "error") %>.
    </div>
    <ul>
    <% @pharmacy.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>
<h1>about</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div id="main-content" class="container">
  <div class="jumbotron">
    <!--<img src="images/freestocks-org-126848-unsplash.jpg" alt="drugs-phote"
    id="sm-img" class="img-responsive visible-xs">-->
    <%= image_tag "freestocks-org-126848-unsplash.jpg", :class => 'img-responsive visible-xs'%>
      <h1 id="jumbotron-h1">Join us and get located anywhere</h1>
      <p id="jumbotron-id">Are you ready to skyrocket your pharmacy? Click below to join us or learn more</p>
      <br>
      <p><%=link_to "join »", signup_path, class:"btn btn-primary btn-lg jumbo-btn", role:"button"%> <a class="btn btn-primary btn-lg jumbo-btn" href="#" role="button">Learn more »</a></p>
  </div>

  <br>
  <br>
  <div id="home-tiles" class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
      <a href="#"><div id="clients-tile"><span>OUR CLIENTS</span></div></a>
    </div>

    <div class="col-md-4 col-sm-6 col-xs-12">
      <a href="#"><div id="info-tile"><span>INFO</span></div></a>
    </div>

    <div class="col-md-4 col-sm-12 col-xs-12">
      <a href="https://www.google.com.gh/maps/@5.7984684,-0.1257998,15z?hl=en&hl=en" target="_blank">
        <div id="map-tile">
          <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d15877.616220995444!2d-0.1257998!3d5.798468399999999!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sgh!4v1521535929261" width="100%" height="250" frameborder="0" style="border:0" allowfullscreen></iframe>
          <span>MAP</span>
        </div>
      </a>
    </div>

  </div><!--end of home tiles-->
</div><!--end of main page-->




<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/script.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>

app/views/static_pages/services.html.erb
<% provide(:title, "Services") %>
<h1>Sevices</h1>